if isdirectory(expand('~/.vim/bundle/vim-pathogen'))
	set rtp+=~/.vim/bundle/vim-pathogen
	execute pathogen#infect()
endif

set nocompatible
syntax on
filetype plugin indent on

"set number
"set relativenumber
set undofile
set hlsearch
set incsearch
set smartcase

set showcmd
set wildmenu
set ruler

set clipboard=unnamedplus

" map
let mapleader=","
map j gj
map k gk

" vars
let g:NERDCustomDelimiters = {
    \ 'phtml': { 'left': '<?php /*', 'right': '*/ ?>' }
\ }

" " if in graphical environment, use light theme. else, use dark
" if $DISPLAY != ""
" 	set background=light
" else
" 	set background=dark
" endif
set background=dark

"let g:solarized_termcolors=256 " use if not using Solarized in terminal emulator
"let g:solarized_termtrans=1
" ignore errors, gracefully fall back
silent! colorscheme solarized

" force markdown ~https://github.com/tpope/vim-markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
" force go
autocmd BufNewFile,BufReadPost *.go set filetype=go
" force ArnoldC
autocmd BufNewFile,BufReadPost *.arnoldc set filetype=arnoldc
" Django syntax highlighting
autocmd BufNewFile,BufReadPost */dev/py/*/templates/*.html set filetype=htmldjango

" set better cache dirs
set directory=~/.vim/swap
set backupdir=~/.vim/backup
set viewdir=~/.vim/view
set undodir=~/.vim/undo
set viminfo+=n~/.vim/viminfo
" easytags.vim
let g:easytags_file = '~/.vim/tags'

" YouCompleteMe
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_collect_identifiers_with_syntax = 1
let g:ycm_complete_in_comments = 1
let g:ycm_complete_in_strings = 1

" matchit.vim
source $VIMRUNTIME/macros/matchit.vim
