" vars
let g:NERDCustomDelimiters = {
    \ 'phtml': { 'left': '<?php /*', 'right': '*/ ?>' }
\ }

" -- Vundle --
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
"Plugin 'tpope/vim-fugitive'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdcommenter'
Plugin 'Valloric/YouCompleteMe'
Plugin 'bronson/vim-visual-star-search'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'tpope/vim-unimpaired'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'
Plugin 'sukima/xmledit'
"Plugin 'kien/ctrlp.vim'
"Plugin 'Lokaltog/vim-easymotion'
Plugin 'pangloss/vim-javascript'
"Plugin 'StanAngeloff/php.vim'
"Plugin 'shawncplus/phpcomplete.vim'
"Plugin 'dsawardekar/wordpress.vim'
Plugin 'editorconfig/editorconfig-vim'
"Plugin 'scrooloose/syntastic'
Plugin 'chase/vim-ansible-yaml'
"" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
"" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
"" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
"" The sparkup vim script is in a subdirectory of this repo called vim.
"" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'vimperator/vimperator-labs', {'rtp': 'vimperator/contrib/vim/'}
"~ " Avoid a name conflict with L9
"~ Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
" -- Vundle --

syntax enable

set clipboard=unnamedplus
"set number
"set relativenumber
set undofile
set hlsearch
set incsearch
set smartcase

set showcmd
set wildmenu
set ruler

" map
let mapleader=","
map j gj
map k gk

"if has('gui_running')
if $DISPLAY != ""
	set background=light
else
	set background=dark
endif

"let g:solarized_termcolors=256 " use if not using Solarized in terminal emulator
colorscheme solarized

" force markdown ~https://github.com/tpope/vim-markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Django syntax highlighting
autocmd BufNewFile,BufReadPost */dev/py/*/templates/*.html set filetype=htmldjango

" set better cache dirs
set directory=~/.vim/swap
set backupdir=~/.vim/backup
set viewdir=~/.vim/view
set undodir=~/.vim/undo
set viminfo+=n~/.vim/viminfo

" YouCompleteMe
let g:ycm_collect_identifiers_from_tags_files = 1
let g:ycm_collect_identifiers_with_syntax = 1
let g:ycm_complete_in_comments = 1
let g:ycm_complete_in_strings = 1

" matchit.vim
source $VIMRUNTIME/macros/matchit.vim

" easytags.vim
let g:easytags_file = '~/.vim/tags'

